Repository arduino-libraries/ArduinoBLE, pull requests merged in 2021-12, with the labels that each got.

#211 fix of bad indexing in ATTClass::handleNotifyOrInd which affected BLE…
  src/utility/ATT.cpp
Labels: bug

#212 Adding sync-labels workflow for sharing one set of labels across all repos.
  .github/workflows/sync-labels.yml
Labels: enhancement

#215 Use major version ref of `carlosperate/download-file-action`
  .github/workflows/sync-labels.yml
Labels: type: enhancement, topic: infrastructure

#216 Configure Dependabot to check for outdated actions used in workflows
  .github/dependabot.yml
Labels: type: enhancement, topic: infrastructure
