Repository arduino-libraries/ArduinoBLE, pull requests merged in 2022-05, with the labels that each got.

#183 Adv data retrieve
  src/BLEDevice.cpp
  src/BLEDevice.h
Labels: type: enhancement, topic: code

#134 Add enhanced advertising examples
  examples/Peripheral/Advertising/EnhancedAdvertising/EnhancedAdvertising.ino
  examples/Peripheral/Advertising/RawDataAdvertising/RawDataAdvertising.ino
Labels: type: enhancement, topic: documentation

#237 Bugfix: memory leak caused by variables not being deleted in end()
  src/BLECharacteristic.cpp
  src/BLEDescriptor.cpp
  src/BLEService.cpp
  src/local/BLELocalCharacteristic.cpp
  src/local/BLELocalService.cpp
  src/remote/BLERemoteCharacteristic.cpp
  src/remote/BLERemoteDevice.cpp
  src/remote/BLERemoteService.cpp
  src/utility/GATT.cpp
  src/utility/HCICordioTransport.cpp
Labels: type: imperfection, criticality: high, topic: code
