Repository arduino-libraries/ArduinoBLE, pull requests merged in 2025-04, with the labels that each got.

#386 fix(HCI): missing LE_Event_Mask
  src/utility/HCI.cpp
  src/utility/HCI.h
Labels: type: imperfection, topic: code

#387 fix: signed and init field warnings
  src/utility/HCI.cpp
  src/utility/L2CAPSignaling.cpp
  src/utility/btct.cpp
Labels: type: imperfection, topic: code

#374 Fix for BLE restart after a BLE end on portenta based devices
  src/utility/HCICordioTransport.cpp
Labels: type: imperfection, topic: code

#376 Clear characteristic cccd value when disconnect
  src/utility/ATT.cpp
Labels: type: imperfection, topic: code

#384 fix: compilation error when using _BLE_TRACE
  src/utility/L2CAPSignaling.cpp
Labels: type: imperfection, topic: code

#291 Update docs for BLECharacteristic constructor
  docs/api.md
Labels: type: imperfection, topic: documentation

#392 Make writeValue return the number of bytes written
  extras/test/CMakeLists.txt
  extras/test/src/test_characteristic/test_writeValue.cpp
  src/local/BLELocalCharacteristic.cpp
  src/utility/ATT.cpp
  src/utility/ATT.h
Labels: type: enhancement, topic: code

#394 fix: keywords.txt
  keywords.txt
Labels: type: imperfection, topic: code
